messages:
  no-permission: "&cYou do not have permission to do this!"
  player-not-found: "&cPlayer not found."
  reloaded: "&aSuccessfully reloaded config."
  inventory-not-empty: "&cYour inventory must be empty to switch to creative mode."
  protection-enabled: "&aYou have enabled creative mode protection."
  protection-disabled: "&cYou have disabled creative mode protection."

clear-effects-on-switch: true # Clears all potion effects when switching gamemodes.

# If you wish the feature to work in all worlds, leave the list empty.
prevent:
  # Prevents switching to creative mode if the player has items in their inventory.
  # Bypass permission: safecreative.bypass.gamemode-switch-empty
  switch-creative-with-items: true
  # Prevents switching to survival mode if the player has items in their inventory.
  # Bypass permission: safecreative.bypass.gamemode-switch-empty
  switch-survival-with-items: true
  # Prevents breaking containers.
  # Bypass permission: safecreative.bypass.container-break
  breaking-containers:
    enabled: true
    survival: true # Prevents breaking containers in survival mode.
    creative: true # Prevents breaking containers in creative mode.
    only-not-empty: true # Prevents breaking containers only if they are not empty.
    message-not-empty: "&cYou cannot break this container because it is not empty."
    clear-contents-on-break: true # Clears the contents of the container when broken.
    set-to-air: true # Sets the container to air when broken (or attempted to break).
    worlds:
      - creative
  # Prevents item pickup.
  # Bypass permission: safecreative.bypass.item-pickup
  item-pickup:
    enabled: true
    creative: true # Prevents item pickup in creative mode.
    survival: true # Prevents item pickup in survival mode.
    adventure: true # Prevents item pickup in adventure mode.
    tagged-items-only: true # Whether to only prevent pickup of tagged items in survival mode.
    destroy: true # Whether to destroy the item after attempting to pick it up.
    worlds:
      - creative
  # Prevents potion throwing.
  # Bypass permission: safecreative.bypass.potion-throw
  potion-throw:
    enabled: true
    creative: true # Prevents throwing potions in creative mode.
    survival: true # Prevents throwing potions in survival mode.
    message: "&cYou can't throw potions in here."
    worlds: # Prevents throwing potions in these worlds.
      - creative
  # Prevents potion drinking.
  # Bypass permission: safecreative.bypass.potion-drink
  potion-drink:
    enabled: true
    creative: true # Prevents throwing potions in creative mode.
    survival: true # Prevents throwing potions in survival mode.
    message: "&cYou can't drink potions in here."
    worlds: # Prevents drinking potions in these worlds.
      - creative
  # Prevents item dropping.
  # Bypass permission: safecreative.bypass.bow-shoot
  bow-shoot:
    enabled: true
    creative: true # Prevents shooting bows in creative mode.
    survival: true # Prevents shooting bows in survival mode.
    crossbow: true
    message: "&cYou can't shoot bow here."
    worlds: # Prevents shooting bows in these worlds.
      - creative
  # Prevents item dropping.
  # Bypass permission: safecreative.bypass.item-drop
  item-drop:
    enabled: true
    creative: true # Prevents item drop while in creative mode.
    survival: true # Prevents item drop while in survival mode.
    message: "&cYou can't drop items here."
    worlds: # Prevents item drop in these worlds.
      - creative
  # Prevents command execution.
  # Bypass permission: safecreative.bypass.command-execution
  command-execution:
    enabled: true
    creative: true # Prevents command execution while in creative mode.
    survival: true # Prevents command execution while in survival mode.
    message: "&cYou can't use this command here."
    worlds: # Prevents command execution in these worlds.
      - creative
    commands:
      all: false # Prevents all commands, whether they're listed or not.
      # If true (blacklist), it will only block the commands listed below.
      # Else, it will block all commands except the ones listed below.
      blacklist: true
      list:
        - '/auction'
  # Prevents portal creation.
  # Bypass permission: safecreative.bypass.portal-creation
  portal-creation:
    enabled: true
    creative: true # Prevents creative players from creating portals.
    survival: true # Prevents survival players from creating portals.
    message: "&cYou can't create portals here."
    worlds: # Prevents portal creation in these worlds.
      - creative
  # Prevents players from opening containers (chests, furnaces, anvils, etc.) in creative mode.
  # Bypass permission: safecreative.bypass.container-open
  opening-containers:
    enabled: true
    creative: true
    survival: true
    message: "&cYou can't open containers here."
    worlds:
      - creative
  # Prevents creative mode players from flying.
  # Will prevent all kind of attempts to fly.
  # Bypass permission: safecreative.bypass.fly
  fly:
    enabled: false
    message: "&cYou can't fly in here."
    worlds:
      - creative
  # Prevents players from interacting with item frames and armor stands.
  # Bypass permission: safecreative.bypass.interact-frame-armor-stand
  interact-frame-armor-stand:
    enabled: true
    creative: true
    survival: true
    message: "&cYou can't interact with item frames and armor stands here."
    worlds:
      - creative
  # Prevents players from damaging animals, mobs, and other players.
  # Bypass permission: safecreative.bypass.damage
  damage:
    enabled: true
    creative: true
    survival: true
    animals: true
    mobs: true
    players: true
    message: "&cYou can't damage entities here."
    worlds:
      - creative
  # Prevents experience orbs from being picked up.
  # Bypass permission: safecreative.bypass.exp-pickup
  exp-pickup:
    enabled: true
    creative: true
    survival: true
    worlds:
      - creative
  # Prevents fishing.
  # Bypass permission: safecreative.bypass.fishing
  fishing:
    enabled: true
    creative: true
    survival: true
    only-players: true # Whether to only prevent fishing players.
    worlds:
      - creative
  # Prevents breaking creative-mode placed blocks in survival mode.
  # Bypass permission: safecreative.bypass.survival-break-creative-placed
  survival-break-creative-placed:
    enabled: true
    set-to-air: true # Whether to destroy the block when breaking it or just cancel the break.
    message: "&cBroken block was placed in creative."
  # Prevents all kinds of entities (mobs, falling sand, item drops) from spawning and appearing in defined worlds.
  entity-spawn:
    enabled: true
    entities:
      all: true # Prevents all entities from spawning, whether they're listed or not.
      # If true (blacklist), it will only block the entities listed below.
      # Else, it will block all entities except the ones listed below.
      blacklist: true
      # Entity names can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
      list: []
    worlds:
      - creative


# Prevents items from being taken in creative mode.
# Bypass permission: safecreative.bypass.item-restriction
restricted-items:
  enabled: true
  message: "&cYou can't use this item in creative mode."
  list:
  - BEACON
  - BEDROCK
  - OAK_BOAT
  - SPRUCE_BOAT
  - BIRCH_BOAT
  - JUNGLE_BOAT
  - ACACIA_BOAT
  - DARK_OAK_BOAT
  - TOTEM_OF_UNDYING
  - ENDER_CHEST